version: "3"

services:
  # api:
  #   build: ./api
  #   ports:
  #     - "5000:5000"
  dashboard:
    container_name: dashboard
    build: ./dashboard
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync+restart
          path: ./dashboard
          target: /dashboard
          ignore:
            - node_modules
