version: "3"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  api:
    container_name: api
    build: ./api
    ports:
      - 5000:5000
  dashboard:
    container_name: dashboard
    build: ./dashboard
    ports:
      - 5173:5173
    develop:
      # This hot reloads dashboard for devlopment
      # Run with docker compose watch
      watch:
        - action: sync+restart
          path: ./dashboard
          target: /dashboard
          ignore:
            - node_modules
